openapi: 3.0.3
info:
  title: Template Server - OpenAPI 3.0
  description: |-
    This is a sample Server based on the OpenAPI 3.0 specification. 
  
  version: 1.0.12
servers:
  - url: https://localhost:8080/api/v1
tags:
  - name: user
    description: user
  - name: ping
    description: ping
paths:
  /ping:
    get:
      tags:
        - ping
      summary: Check if the server is running
      description: Ping with server.
      operationId: getPing
      responses:
        '200':
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
                example: pong
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /users:
    get:
      tags:
        - user
      summary: Get user information
      description: Retrieve user information.
      operationId: listUsers
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                $ref: "#/components/schemas/User"
              example:
                - id: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                  name: "root"
                - id: "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy"
                  name: "yyyy"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
      required:
        - id
        - name
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
